image: php:7.2

services:
  - php
  - mysql

before_script:
  - chmod +x phpunit.phar
  - docker-php-ext-install pdo_mysql
  - docker-php-ext-install mysqli
  
stages:
  - test

test:
  script:
  - ./phpunit.phar --configuration phpunit.xml